### ISSUE TITLE
Doesn't Work with IE8

### ISSUE THREAD

**Issue by JonesXavi** [kmewhort/pointer_events_polyfill#16]
This does not work in IE 8. I made all the anchor tags to pointer-events:none; It supports IE 9 though. But I need for IE 8. Please check this out.

**Comment by entozoon** [comment]
Hi, I've forked this repository and added IE8 support - https://github.com/entozoon/pointer_events_polyfill

Use this updated js, and also add a data-pointer-events-none attribute to your element. e.g.
````
<div data-pointer-events-none></div>
````

**Comment by cvrebert** [comment]
Duplicate of #2.

**Comment by yolo2013** [comment]
@entozoon Hi, your update makes it work fine on IE8 just click、mousedown event. But Have you think this need a mouseover or hove?

**Comment by entozoon** [comment]
@yolo2013 In those situations you might be better to override for IE8 elsewhere, such as with a CSS hack or detect the browser with a javascript library.
